export const GET_FLOOR_LIST_INITIATED= "GET_FLOOR_LIST_INITIATED"
export const GET_FLOOR_LIST_SUCCESS= "GET_FLOOR_LIST_SUCCESS"
export const GET_FLOOR_LIST_ERROR= "GET_FLOOR_LIST_ERROR"


export const GET_EMPLOYEE_INITIATED = "GET_EMPLOYEE_INITIATED";
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS";
export const GET_EMPLOYEE_ERROR = "GET_EMPLOYEE_ERROR";



